openapi: 3.0.0
info:
  title: Prisma Cloud Defender API
  version: 1.0.0
  description: |
    This API specification defines endpoints for managing resources and ensuring compliance using Prisma Cloud Defender.
servers:
  - url: https://api.example.com/v1
    description: Production server
paths:
  /resources:
    get:
      summary: Get list of resources
      description: Retrieves a list of resources managed by Prisma Cloud Defender.
      responses:
        '200':
          description: A list of resources
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Resource'
      tags:
        - Resources
    post:
      summary: Create a new resource
      description: Creates a new resource to be managed by Prisma Cloud Defender.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceInput'
      responses:
        '201':
          description: The newly created resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
      tags:
        - Resources
  /resources/{resourceId}:
    get:
      summary: Get details of a resource
      description: Retrieves details of a specific resource.
      parameters:
        - name: resourceId
          in: path
          description: The ID of the resource to retrieve.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details of the specified resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
      tags:
        - Resources
    put:
      summary: Update a resource
      description: Updates the details of a specific resource.
      parameters:
        - name: resourceId
          in: path
          description: The ID of the resource to update.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceInput'
      responses:
        '200':
          description: The updated resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
      tags:
        - Resources
    delete:
      summary: Remove a resource
      description: Removes a specific resource from the system.
      parameters:
        - name: resourceId
          in: path
          description: The ID of the resource to remove.
          required: true
          schema:
            type: string
      responses:
        '204':
          description: The resource has been successfully removed.
      tags:
        - Resources
components:
  schemas:
    Resource:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the resource.
        name:
          type: string
          description: The name of the resource.
        type:
          type: string
          description: The type or category of the resource.
        status:
          type: string
          description: The status of the resource.
      required:
        - id
        - name
        - type
        - status
    ResourceInput:
      type: object
      properties:
        name:
          type: string
          description: The name of the resource.
        type:
          type: string
          description: The type or category of the resource.
      required:
        - name
        - type
security:
  - api_key: []

